### ISSUE TITLE
'Read' status when building a new version

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1032]
Whenever I upgrade hubturbo (`gradlew build -x text`), issues marked previously as read becomes unread. This was not the case earlier. I'm guessing it has something to do with recent changes re diff comments? @ndt93

**Comment by ndt93** [comment]
Do all issues become unread or just pull requests?

The changes for re diff involve pulling in updates for pull requests that have never been considered before, so those updates will cause the corresponding pull requests to become unread, but this should be expected behavior and things should settle after a while.

From now on, if you still observe issues become unread even though there are no changes then it should be a bug.

**Comment by damithc** [comment]
I'll observe more and report later.

**Comment by damithc** [comment]
Old issue. closing for now.
