### ISSUE TITLE
Some issues missing from the issue list

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1038]
![image](https://cloud.githubusercontent.com/assets/1673303/10393340/bdad161c-6ec1-11e5-9fee-f0ad05913b50.png)

Did not come back after restarting. But came back after deleting the cache.

**Comment by ndt93** [comment]
The the beginning of the log (which is about 6pm and is after those issues were created) there is this error message:
>104412140 09/10/2015 17:46:03 ERROR HTLog [pool-4-thread-133] - API rate limit exceeded for 137.132.223.229. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) (403)
org.eclipse.egit.github.core.client.RequestException: API rate limit exceeded for 137.132.223.229. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) (403)

which I'm not sure about  its exact meaning and effect (there are still 3617 quota left). Right afterwards, the `nus-cs2103/website` repo's issues are updated with the ETag `382bae56cdbb93ed2b19b8ac6476eae0` and reports `Nothing to update`. So either it has to something to do with the error or the problem already occured before any event recorded in the log i.e. The ETag has been updated but the issues are not updated accordingly.

Another thing is that we are using ETag to check for issues updates which makes things more complex while not really useful since we have the `since` parameter. We can remove the ETag mechanism and if this bug is related to ETag then it should help.

**Comment by damithc** [comment]
Anyone working on this?

**Comment by dariusf** [comment]
I think I added this to the milestone by mistake. No one working on it, but @ndt93's fix in #1042 eliminates one source of error, so we can see if the problem still persists.

**Comment by damithc** [comment]
Old issue. closing for now.
