### ISSUE TITLE
Panel UI becomes blank when switching repo

### ISSUE THREAD

**Issue by ndt93** [HubTurbo/HubTurbo#1056]
This happens on both Windows and Linux without any filter, and I think might be a separate problem from #934 . Step to reproduce:

1. Open `teammates/repo` using repo selector box.
2. Switch to `hubturbo/hubturbo` using repo selector box. Right after that, try to scroll the Panel UI (by using the middle mouse button for example).
3. The Panel UI will be blank and a loud crash occurs (check the log).

This could have happened before, but may be I only realize it recently since it takes more time to switch repos now so I get impatient and scroll my mouse around.

**Comment by damithc** [comment]
Tried the steps. Doesn't happen in my machine (Win7). But if you can reproduce it, then we need to fix.

**Comment by HansNewbie** [comment]
I can reproduce it in Mac. I think it's because of #1028 where repo model is deleted when changing default repo, but the `ListPanelCell` is still referencing the model. I can think of 2 options: either clear panel issues upon changing default repo or put the model deletion as pending until the new repo is loaded.
