### ISSUE TITLE
milestone aliases don't work when there are no open milestones

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1081]
When there are no open milestones, `milestone:current` should yield zero issue while `milestone:current-1` should yield the previous milestone. That doesn't seem to be the case now.

**Comment by HansNewbie** [comment]
Right now, if there are no open milestones, I set `milestone:current` to last milestone.

Instead, `milestone:current` should contains nothing while `milestone:current-1` should get the last milestone in the list?

**Comment by damithc** [comment]
Yes, we can consider closed milestones are no longer current?
BTW, due date is optional so we need a decent fallback mechanism if there are no due dates. However, that can be a separate issue.
Currently, there are no open milestones in HT so I get a milestone without due date as the current milestone :-p

**Comment by HansNewbie** [comment]
Right now, I sort the milestone from with due date to no due date, so milestones with no due date will always be at the end/"future". So what happens with HT now is that there are some milestones with no due dates, and since there are no open milestones, it will just grab the last milestone in the list, which is the one with no due date.

So what should we do for milestone with no due date? Some options I can think of:
- exclude them entirely
- list them older than milestones with no due date
- exclude them entirely but make a different alias for it (may be `dateless` alias)

**Comment by HansNewbie** [comment]
As discussed, will exclude them from milestone alias.
