### ISSUE TITLE
Issues from the current milestone not matching the alias

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1116]
![image](https://cloud.githubusercontent.com/assets/1673303/10959255/87ed5c76-83b1-11e5-9f48-5ca4bff2e8fa.png)

**Comment by HansNewbie** [comment]
@damithc a pull request removes the milestone alias feature. #1047 removes the call to milestone alias resolver, so it is not working right now. Will see how the new code works and put accordingly.

**Comment by damithc** [comment]
How did it pass the tests?

**Comment by HansNewbie** [comment]
There is no GUI test that tests milestone alias.

In its implementation, milestone alias is resolved before issue matching. This call to milestone alias resolver and issue matching is within GUI. However, it was deemed unnecessary to create a GUI test since testing that the alias works can be done by converting a filter with alias and pass it to the issue matcher (`Qualifier.process`) and there is no GUI element that needs to be tested.

Even now, the only way to ensure this does not happen again is by implementing a GUI test. Should a GUI test be made to ensure this does not happen again?

**Comment by damithc** [comment]
This is an example of why unit testing is not enough. Integration tests are needed too. Yes, we should create a GUI test or modify an existing test to cover this aspect.

**Comment by HansNewbie** [comment]
Okay, will do.
