### ISSUE TITLE
Ensure MultiModel correctness

### ISSUE THREAD

**Issue by acruis** [HubTurbo/HubTurbo#1132]
Via the use of a logical queue, which simply keeps track of all async operations. When an async operation is to be carried out (in its own worker thread), it checks against the logical queue to see if it can be carried out immediately, or whether it should wait until some prior tasks should finish first.

One of two issues proposed to solve #1089

**Comment by dariusf** [comment]
I am working on this now. The plan is to have repository-level synchronisation for these operations, so they don't interleave. This is enough to ensure correctness.

I don't think we'll reorder the queue or preemptively run operations now, since we couldn't agree on anything concrete last time.

An optimisation we can have is to look for patterns in the queue and drop redundant operations. For example, if we enqueue an update and see a deletion before it, we can remove the latter. This can also be done separately.

**Comment by acruis** [comment]
Yep, I agree that repo-level synchronisation is enough.
