### ISSUE TITLE
filter syntax: Support a shorter form of OR

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1137]
e.g. `repo:repo1,repo2,repo3` or `repo:repo1|repo2|repo3`
This can be particularly useful when we create a panel with selected issues. `id:124,3245,6452,7689`

**Comment by raisfathin** [comment]
I think the second form is not possible since we can't tell whether it means we are "looking for issues from repo1 or repo2", or "looking for issues from repo1 with repo2 in the issue title".

Is the first form supposed to be applicable to all qualifiers? We already have similar syntax with sort, and that will cause this form to have different meanings according to the qualifier type.

**Comment by damithc** [comment]
May be use `;` instead? @dariusf your comments?

**Comment by dariusf** [comment]
I'm assuming that we can expand `a:b;c` to `a:b OR a:c` during the parsing stage. That way this change is completely syntactic and we don't have to store any extra information.

One concern with `;` is negated qualifiers, like `no`. `no:label;milestone` is a bit unintuitive because we'd expect `;` to mean AND in that case.

Apart from that, I can't think of any problems. Using a new token helps.

**Comment by damithc** [comment]
Assuming labels can have `;`, would this `label:a;"b;c"` expand into `label:a OR label:b;c`?

**Comment by dariusf** [comment]
That makes sense, but would have to be implemented.

#1194 would affect it for cases where what is quoted isn't unambiguously a string. For example, `updated:1;"2"` would be invalid.

**Comment by damithc** [comment]
I see. I'm ok with using `;`. @dariusf please advise @raisfathin as to how to proceed.

**Comment by dariusf** [comment]
The problem is adding the semicolon separation to all cases while keeping things as DRY as possible (i.e. not inlining it into each parsing action).

The most direct solution I can think of is to abstract over the parsing action.

```java
FilterExpression separated(Supplier<QualifierContent> action) {
    FilterExpression expr = action.get().createQualifier();
    while (lookAhead().getType() == TokenType.SEMICOLON) {
        consume();
        expr = new Disjunction(expr, action.get().createQualifier());
    }
    return expr;
}
```

`QualifierContent` is the raw content of a qualifier: a date range, number, string, etc. We need it because we want to treat different types of content uniformly during parsing, when we can't construct the full qualifier yet. Each of these objects knows how to construct the qualifier it represents. This is the verbose part.

```java
class QualifierContent {
    QualifierType type;
    Optional<String> contents;
    Optional<DateRange> date;
    // ...

    public FilterExpression createQualifier() {
        if (contents.isPresent()) {
            return new Qualifier(type, contents.get());
        } else if (date.isPresent()) {
            return new Qualifier(type, date.get());
        }
        // ...
    }
}
```

Each of the parsing actions [here](https://github.com/HubTurbo/HubTurbo/blob/master/src/main/java/filter/Parser.java#L179-L209) is changed to return `QualifierContent`.

Then we can add the behaviour to all parsing actions without changing this function much.

```java
private FilterExpression parseQualifierContent(...) {
    if (...) {
        // ...
    } else if (isRangeOperatorToken(lookAhead())) {
        // Previously:
        // return parseRangeOperator(type, lookAhead());
        // Now:
        return separated(() -> parseRangeOperator(type, lookAhead()));
    }
    // ...
}
```

@raisfathin feel free to improve on this!

**Comment by raisfathin** [comment]
@dariusf Thanks! Working on it now.

**Comment by raisfathin** [comment]
I think parsing `label:"x;y"` is not possible right now due to the way the program parses quoted content.

```java
private FilterExpression parseQuotedContent(QualifierType type) {
    StringBuilder sb = new StringBuilder();
    while (!isQuoteToken(lookAhead())) {
        sb.append(consume().getValue()).append(' ');
    }
    return new Qualifier(type, sb.toString().trim());
}
```

The parser appends whitespace after every token which makes `"x;y"` to be parsed as `x ; y` after trimming.

One solution that I can think of right now is that we can make another token for the whitespace (with very low priority?) and move the responsibility of skipping white space from `lexer` to the `consume()` method in the `parser` as argument. The resulting consume method would be something like this :

```java
private Token consume(boolean skipWhitespace) {
    if (skipWhitespace) {
        while (input.get(position) == TokenType.Whitespace) {
            position++;
            sourcePosition += token.getValue().length();
        }
    }
    Token token = input.get(position++);
    sourcePosition += token.getValue().length();
    return token;
}
```

This way, parsing quoted content (with `skipWhitespace = false`) will result in the exact same string typed by the user.

What do you think?

**Comment by dariusf** [comment]
That would work. Ideally we want the parser to be oblivious to whitespace still, i.e. `consume` and `lookAhead` never produce whitespace tokens normally, so existing code doesn't have to be changed. We can then add another method which does take whitespace into account, and use that for quoted strings.

Another consideration: if we are going to implement #1194, this can be handled much more simply in the lexer, since a quoted string would appear be a single token. Maybe we can wait for the outcome of that PR?

**Comment by raisfathin** [comment]
That approach seems to be better for this issue.

Okay, will wait for that PR to be resolved first.
