### ISSUE TITLE
Fix parser not parsing number in quote as string 

### ISSUE THREAD

**Issue by jinified** [HubTurbo/HubTurbo#1194]
Causes filter expression to return false when matching with issue. For example: 

- I have an issue with body that contains the string `normalize output into (0 - 255)`.
- Filter expression: `body:"0"`

**Comment by jinified** [comment]
Here an issue that I encountered after fixing the issue, the [FilterParserTest](https://github.com/HubTurbo/HubTurbo/blob/release/src/test/java/tests/FilterParserTests.java#L48) failed because `content` in quotation is expected to be parsed as Date or DateRange. I personally feel that `content` in quotation should be treated as string.

**Comment by dariusf** [comment]
The root problem is that we don't have a way to have tokens which appear in syntax, like `:` and `&&`, as keywords. I think this is a good idea. Can you think of any other edge cases where we would want a quoted portion to be interpreted as syntax instead of a string?

There's some discussion on this [here](https://github.com/HubTurbo/HubTurbo/issues/1137#issuecomment-174111547). If all we need is a string, this can be handled in the lexer. That would simplify many things.
