### ISSUE TITLE
Use waitAndAssertEquals(...) instead of wait(...) in guitests.ChromeDriverTest

### ISSUE THREAD

**Issue by YijinL** [HubTurbo/HubTurbo#1385]
As mentioned [here](https://github.com/HubTurbo/HubTurbo/pull/1340#issuecomment-198695027).

**Comment by YijinL** [comment]
@acruis was there a reason you used `sleep(1000)`? Can you foresee if this change breaks anything? 

I've already done the refactoring but it always times out on the 9th/10th/11th `waitAndAssertEquals` call. Shuffling the order of the different `waitAndAssertEquals` calls still results in the same behaviour; whichever call is around the 10th place times out. (no individual subtest seems to be causing the issue)

**Comment by YijinL** [comment]
Here is the [diff](https://github.com/YijinL/HubTurbo/commit/0ed15091e7a658c5ca5f0b2331859f141ecf393b) of my commit.

**Comment by acruis** [comment]
Does it happen just on Travis? Or does it occur even when run locally?

**Comment by YijinL** [comment]
Run locally, >6 tries.

**Comment by acruis** [comment]
What do you mean? It passes more than 6 times, or it fails more than 6 times?

**Comment by YijinL** [comment]
Oops I mean this behaviour (the 9-11th ordered waitAndAssertEquals will fail) remains consistent across 6 tries

**Comment by acruis** [comment]
I see. Looking at blame records, I'm sure I just chose `sleep` because there was no `waitAndAssertEquals` at the time (around 9 months ago).

It's either a problem with `waitAndAssertEquals` itself, or it's a problem with firing the test events. You can probably print out some output during event firing to see whether the event was successfully fired (which means the problem lies in `waitAndAssertEquals`), or whether the UI thread is busy with other computations.

**Comment by YijinL** [comment]
After a lot more debugging, I realised that it's not only the 9-11th `waitAndAssertEquals` that fails; every test involving `script` checks or `url` checks may fail, and the probability follows a normal distribution (citation needed) along the order of test execution.

It seems to be caused by `BrowserComponent`, `ChromeDriverEx`, and `UI` threads interfering with each other. Sometimes this series of event happens:
```
5416 23/03/2016 01:03:54 WARN BrowserComponent [pool-9-thread-1] - Unable to reach bview. 
5416 23/03/2016 01:03:54 INFO BrowserComponent [pool-9-thread-1] - Chrome window not responding.
5416 23/03/2016 01:03:54 INFO BrowserComponent [pool-9-thread-1] - Relaunching chrome.
5416 23/03/2016 01:03:54 INFO BrowserComponent [pool-9-thread-1] - Quitting browser component
5416 23/03/2016 01:03:54 INFO BrowserComponent [pool-9-thread-1] - Logging in on GitHub...
5416 23/03/2016 01:03:54 INFO BrowserComponent [pool-9-thread-1] - Bringing bView to front
5416 23/03/2016 01:03:54 INFO BrowserComponent [pool-9-thread-1] - Failed to bring bView to front.
5416 23/03/2016 01:03:54 INFO BrowserComponent [pool-9-thread-1] - 1400
```
and when trying to reset the browser and login again, more `NavigateToPageEvent`s and `ExecuteScriptEvent`s are created which change the last executed scripts/urls, so the test never sees the script/url used.

I see a few ways to move forward:
- Fix `BrowserComponent` having trouble reaching `bview`
- Somehow capture only the next script/url change event after each test input so the result isn't overwritten
- Don't capture those event types (I don't know how else to do it tho)

I will try number 2 first, it has the highest chance of success. Probably gonna use some `AtomicReference` magic or have the event handlers unregister themselves when they fire and then manually register them again before the next test case.

**Comment by acruis** [comment]
I agree, number 2 sounds good.

If we're just checking that `script` and `url` are being called, it's even possible to change the `script = e.script` handler to something like `scriptValues.append(e.script)` where `scriptValues` is an `ArrayList`. That way, we don't overwrite old values, and instead of an equals check, we do a `contains` check, and then clear the `ArrayList` after each test.

**Comment by YijinL** [comment]
Yes that seems best. I will still purge the `script/urlValues` collection between each test.
