### ISSUE TITLE
'Go to file view' keyboard shortcut is broken 

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1393]
Looks like it's broken again. Github changed the page DOM again?

**Comment by HansNewbie** [comment]
Yes. The DOM change very slightly. This problem actually will be solved if we solve #1375. The downside is that if we open the URL instead of clicking the tab, it will be slower since the tabs have AJAX fetching. On the other side, we don't depends on the DOM anymore but rather URL (which is unlikely to change as often).

Do you want a quick fix to the DOM or solve #1375 accounting for the downside?

**Comment by damithc** [comment]
If no one is doing #1375, go ahead and do it. Otherwise do a quick fix until that one is fixed.

**Comment by HansNewbie** [comment]
I will do quick fix.
