### ISSUE TITLE
open/close shortcut: server error does not revert local change

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1433]
For example, I used the 'x' shortcut to close a PR, but the operation fails due to a permission problem, the issue is still shown as closed locally.

**Comment by xinan** [comment]
Okay I found the reason:

`Model` is returning a new copy of `TurboIssue` object, after modifying the state of the issue, using `TurboIssue`'s copy constructor. I added the `stateLastModifiedAt` attribute to keep track of the last modified time for the issue's state so that the logic can decide whether to revert local change or not. However, I forgot to update the copy constructor, so the returned new issue doesn't have an updated `stateLastModifiedAt`. That's why logic decides not to revert local changes.

I will create a PR to fix this in a minute. :sweat_smile:
