### ISSUE TITLE
f/g keys don't work when the focus is in the issue list

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#522]
They should still work right?

**Comment by damithc** [comment]
In fact, even the double space stops working if I tried to use f/d while the focus is on the issue list.

**Comment by damithc** [comment]
Is it f/g or f/d? d conflicts with 'scroll (d)own' right?

**Comment by rd1992** [comment]
it will be f/g now. The problem occurs because we have keyboard shortcuts all over the place. while that is good OOP design, managing them is becoming a pain. We should think about creating all the shortcuts in a separate class as that gives us the flexibility of allowing users to have their own preference for keyboard shortcuts.

**Comment by rd1992** [comment]
I have fixed it for now
