### ISSUE TITLE
RepositorySelector only shows one repo on restart

### ISSUE THREAD

**Issue by lejolly** [HubTurbo/HubTurbo#619]
Even though there's more than one in `config/global.json`

**Comment by ianngiaw** [comment]
Would it be better if we changed `ui.logic.getOpenRepositories()` in `RepositorySelector`'s loadContents method to something like `getLastViewedRepositories()`?

**Comment by acruis** [comment]
Related to #665. Fixes on the repo selector might not be easy to check before #665 gets solved.

**Comment by HyungJon** [comment]
More specifically, only the repositories accessed at startup (i.e. default repo and any that were opened through column filters) are displayed.

I also think retrieving the list from getLastViewedRepositories() is a good choice. It would also be good if logging out purges the list as well as user credentials so that the user can empty the drop-down list.

**Comment by lejolly** [comment]
Fixed via #749
