### ISSUE TITLE
Ignore user's own updates when using the updated filter

### ISSUE THREAD

**Issue by lejolly** [HubTurbo/HubTurbo#679]
May need to be broken down into sub-issues. 

Scenario:
1. user types in `updated:XX sort:date` in filter box
2. user clicks on first issue in panel
3. user comments on said issue

4a. when user focuses back onto HT, currently it detects a change in the page and refreshes the repo/list, and since it was updated, the issue jumps to the bottom, issue selection in the list also changes
4b. what should happen is that when going back to HT, it should still detect a change in the page and refresh, but should not change the order of the list by ignoring the latest update done by the user

**Comment by lejolly** [comment]
@acruis #465 might be related to this?

**Comment by acruis** [comment]
Yep. I'll add a check for comments, too.

**Comment by acruis** [comment]
@damithc: If the only updates within the specified window to an issue are own actions, should it disappear from the issue panel, or should it still be there?

For example, if a panel's filter is `updated:3` and the only changes to an issue inside that panel since 3 hours ago were done by the user, should it disappear from that panel?

**Comment by damithc** [comment]
Yes, should not appear.

**Comment by acruis** [comment]
Alright, that makes things a lot simpler.

**Comment by acruis** [comment]
To make it easier, when using sort by date alone, then we sort according to updated date. This is because we do not have relevant metadata. The metadata (events & comments) is only downloaded when using the `updated:` filter. If we're using the `updated:` filter, then we should, by default, sort by last non-self activity date.

**Comment by damithc** [comment]
Yes, that should be fine.

**Comment by acruis** [comment]
Do we take into account the creation of the issue itself as an update? i.e. if there is a fresh issue that was created within the specified range, but has not been modified at all since creation yet, do we accept it under the filter? My intuition is yes, but would the issue still be accepted by the filter even if it is the user himself who created the issue?

**Comment by damithc** [comment]
To be consistent, an issue created by self should be considered as a self
update and should not appear under the updated filter. If I created an
issue just now, I don't want to have to mark it as read immediately after.

**Comment by acruis** [comment]
Alright.

**Comment by acruis** [comment]
@damithc There is currently a significant split on program behaviour depending on whether we have metadata (i.e. `updated:` specified in the filter). Metadata here refers to issue events and comments (i.e. the additional information requested from GitHub and then presented when `updated:` is specified in the filter).

The current scenario is that when we don't have metadata, we can only sort (and count comments to highlight when necessary) based on the last updated time of the issue, which includes the users' own activity.

We only know the actor behind each event / comment in an issue through the metadata (the presence of which depends on whether `updated:` was specified) and thus only then we can sort based on non-self updates.

This is potentially confusing to the user as the program behaves differently based on whether the `updated:` filter is present.

Our proposed reconciliation is to disable sorting by last updated time, as well as highlighting of the comment bubble, when the `updated:` qualifier is not present in the filter string (i.e. when we do not have metadata).

**Comment by damithc** [comment]
Yes, that should be fine for now.

**Comment by damithc** [comment]
This doesn't seem to be fixed. I have the filter `-sort:updated` and when I add a comment to an issue in the list, it goes to the bottom of the list.

**Comment by acruis** [comment]
What filters are you using?

**Comment by acruis** [comment]
I think you didn't specify the updated window in the filter (e.g. `updated:3`). We only trigger metadata requests based on the updated window (otherwise we'll fire off too many API requests) and so without the updated window, we don't have metadata for the issues (which is where we determine the actor of an update event).

**Comment by acruis** [comment]
The filter to use is `-sort:nonSelfUpdate`.

As discussed, the sort key `nonSelfUpdate` will be removed, and its functionality will be migrated to `sort:updated`. I'll do this in a separate issue.

Do inform me if there are any more problems with non-self updates :)

**Comment by damithc** [comment]
Got it.

**Comment by damithc** [comment]
Now I'm using `-sort:nonSelfUpdate` and still get this problem.
Steps:
  1. Add a comment on bView.
  2. <kbd> Ctrl+Tab </kbd> to switch to pView and hit <kbd>E</kbd> immediately. The issue disappears momentarily, and appears again after a few seconds. 

Possibly something to do with the refresh that is triggered when I switch back to pView?

**Comment by acruis** [comment]
Does the problem occur without hitting <kbd>E</kbd>?

**Comment by damithc** [comment]
Just now I realized this is a slightly different problem. This is no longer about the sort order. The issue should not come back into the view because I marked it as read (the filter has `is:unread`). My own update to the issue is making it come back, which is wrong for two reasons: 
  1. the update was done a few seconds before I hit <kbd>E</kbd>. However, the update might reach the server *after* I hit <kbd>E</kbd> and it most likely reach pView *after* I hit <kbd>E</kbd>.
  2. the update, even if it was registered after I hit <kbd>E</kbd>, was done by me so it should not appear in list due to `-sort:nonSelfUpdate` filter. I know it sounds convoluted and involves the interplay of two filters, but intuitively I don't expect to see that issue in the list. Currently I have to hit <kbd>E</kbd> twice to make such an issue disappear from the view. May be we need a new filter `ignoreSelfUpdates:true` ?

**Comment by acruis** [comment]
`-sort:nonSelfUpdate` does not ensure that self-updates will not be shown. The filter that ensures this is the `updated:XX` filter. (where XX is the time window for filtering) However, I'll assume you have `updated:5` in your filter text.

I think a new filter sounds like a good idea. It doesn't solve the problem, as it would just be doing exactly what the `updated:` filter is doing, but it makes the idea that we're getting metadata much more clearer to the user.

As for the issue itself, I found some bugs with the behaviour of the `updated:XX` filter itself. Will update you when I've pinpointed the cause of the problem.

**Comment by damithc** [comment]
Yes, a new filter wont solve this problem. The root cause for this problem is the race condition between  `E` and the update. Although in reality `E` follows the update, HT sees it as update following the `E` due to the two things taking two different paths to reach HT. When deciding whether an issue is read or unread, we may have to compare the most recent *non-self* update to the timestamp of the last read. This is were a new filter `ignoreSelfUpdates:true` can be applied. If that filter is present, we compare against the last non-self update, otherwise we compare against the latest update.

**Comment by damithc** [comment]
Alternatively, we can use a symbol to indicate 'ignore self update' condition. e.g. `is:read^` vs `is:read` and `sort:updated^` vs `sort:updated`

**Comment by acruis** [comment]
I see what you mean. The problem is that there should be some communication between the behaviours of `is:unread` and `updated:XX`, but there currently isn't.

The bad news is that this is serious enough to warrant its own issue. The good news is implementing this is a lot simpler after the GUI refactoring has been merged. I'll create a new issue.
