### ISSUE TITLE
Show closed/merged issues in a different way

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#680]
Strike out the title? Might reduce the readability though.

**Comment by acruis** [comment]
That's actually a bug. The styling is already present in the CSS file, but it was not being applied to the correct Node on the JavaFX UI. The problem is fixed on the current master branch:

![image](https://cloud.githubusercontent.com/assets/8437638/8074642/e6aa6a24-0f67-11e5-8f9e-02b2a9998700.png)

**Comment by damithc** [comment]
How can we cover this sort of bugs in tests?

**Comment by acruis** [comment]
Anything styleable in JavaFX allows its CSS classes to be accessed through the [getStyleClass()](https://docs.oracle.com/javase/8/javafx/api/javafx/css/Styleable.html#getStyleClass--) method. I'm currently working on making the IssuePanelCards accessible by TestFX, so that we can check the CSS styling of the issue cards.

**Comment by damithc** [comment]
Seems to be fixed in the latest version.
