### ISSUE TITLE
Update .classpath to be compatible with new libraries

### ISSUE THREAD

**Issue by HyungJon** [HubTurbo/HubTurbo#762]
Some changes to code may also be desirable as the new setting results in several more warnings.

**Comment by lejolly** [comment]
What warnings?

**Comment by HyungJon** [comment]
Most are "FutureTask is a raw type. References to generic type FutureTask<T> should be parametrized" warning. That and some "The value is not used" warnings.

**Comment by ndt93** [comment]
You can use the command `gradle eclipse` to generate eclipse config files from the updated *build.gradle*. There is also an official [eclipse extension](https://marketplace.eclipse.org/content/buildship-gradle-integration) for gradle or this more popular [eclipse tooling](https://marketplace.eclipse.org/content/gradle-integration-eclipse-0) for gradle.

Should we remove the eclipse files from the repo all together, and/or mention the above steps in the developer guide? Since it could be confusing for an eclipse user who hope to contribute to this repo and happen to think that the eclipse project files are supposed to be updating.

Eclipse users unite! :P

**Comment by damithc** [comment]
Eclipse files should be updated. Eclipse should be the official IDE of this
project. Normally I insist on all devs using the official IDE, but in this
case I allow using IDEA because it is good for the dev team to have some
hands-on experience with other IDEs.
