### ISSUE TITLE
Detect json explosion

### ISSUE THREAD

**Issue by lejolly** [HubTurbo/HubTurbo#799]
Alert the user, save a copy of the log (last 100/1000 lines?), re-download repo.

**Comment by ndt93** [comment]
I have a bunch of makeshift detection code for this at the moment using the regex and logging locations suggested in #706. I've been logging for the past week but nothing odd has happened, so can't realistically test if the detection code fully works (at least no false positive so far though). I manually corrupted the file and tested but it works simply because I wrote the code first and corrupted the file to fit in later (aka confirmation bias :P).

I'm not sure if checking file size will detect the problem immediately or works in all cases since we haven't been sure if the effect is accumulative.

Has anyone caught anything for this? Could be also that egit or gson or how we use/obtain them that causes the problem.

**Comment by lejolly** [comment]
we're going with a size-based comparison for now (1KB per issue/pr) so we'll see how it goes, as for actually solving it, i think that discussion should take place in #706.

**Comment by acruis** [comment]
@ndt93 The regex doesn't match my corrupted file :( Let's say I store the file data as a string `fileText` then the syntax is like this right?

`System.out.println(fileText.matches("[^\w \v\t\r\f\n"'()+\-,:@\\/#$!^%&*;|<>?=.]{3,}")); // Should print true if json is corrupted`

**Comment by ndt93** [comment]
Oh, if you are putting the regex in a string then the backlash should be double escaped so the string is something like this: `"[^\\w \\v\\t\\r\\f\\n\"\'()+\\-,:@\\/#$!^%&*;|<>?=.]{3,}"`

I think a would way to check/found a suitable regex is using a text editor with incremental highlight regex search like vim or eclipse' vwrapper plugin or tools like `grep`

Anyway, we shall bring this discussion back to #706 :P
