### ISSUE TITLE
keyword search broken for large repos?

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#838]
When trying with homebrew, keyword search does not seem to narrow down search results. e.g. `is:open` and `is:open fix` seem to give the same result set.

**Comment by lejolly** [comment]
yes this seems to be the case when @kanghj tried it too.

**Comment by acruis** [comment]
Turns out this is consistency problem in the current GitHub API. See the response returned when I query `acruis/test/11` (issue ID 11 of my own test repo) against `homebrew/homebrew/9019` (where [9019](https://github.com/homebrew/homebrew/issues/9019) is one of the many issues of Homebrew that causes the NPE):

```
{
  "url": "https://api.github.com/repos/acruis/test/issues/11",
  [...]
  "number": 11,
  "title": "test issue 11",
  [...]
  "body": "",
  [...]
}
```

```
{
  "url": "https://api.github.com/repos/Homebrew/homebrew/issues/9019",
  [...]
  "number": 9019,
  "title": "Add formula for numutils: http://suso.suso.org/programs/num-utils/.
Thanks for pointing this out, @sstephenson!",
  [...]
  "body": null,
  [...]
}
```

This is data we acquire directly from GitHub. Apparently, for some Homebrew issues, an empty body is stored as `null`, whereas for my test repo, an empty issue body is stored as an empty string. I'll make a PR to deal with this.

**Comment by damithc** [comment]
We have similar situations in TEAMMATES. Old data in the database sometimes
follow formats slightly different from that of recent data. Data formats
evolve over time and sometimes old data is not migrated to follow the new
formats. In those cases the code has to deal with all variants of the data
formats.

**Comment by acruis** [comment]
Yup, I agree that the code should be able to handle even old versions of the data. Thanks for the insight :-)
