### ISSUE TITLE
pri.high should match priority.high

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#864]
![image](https://cloud.githubusercontent.com/assets/1673303/9265552/4f72a666-4267-11e5-91f2-4dc423455a37.png)
Even `priority.high` seems to match `Feature.TextHighlight`

**Comment by damithc** [comment]
If not done already, try to extract the matching into a separate function so that it can be enhanced and tested independently of the GUI.

**Comment by dariusf** [comment]
The existing matching function for filters is [here](https://github.com/HubTurbo/HubTurbo/blob/master/src/main/java/filter/expression/Qualifier.java#L618) with [tests](https://github.com/HubTurbo/HubTurbo/blob/master/src/test/java/tests/FilterEvalTests.java#L134). We can either factor it out, or have the label picker make use of it somehow. Currently we're duplicating work a bit.

**Comment by lejolly** [comment]
most of the logic pertaining to the label picker has been abstracted out to `LabelPickerUILogic` which has it's own test in `LabelPickerLogicTests`. it is also using the `TurboIssue.getGroup` as i'm not dealing with actual `TurboLabels` but rather just strings. 

anyway, the bug here is due to not ignoring the case when using `String.startswith`.
